[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gen_arm32asm"
version = "1.0.0"
description = "Your project description"
authors = [{name = "Vladimir Roncevic", email = "elektron.ronca@gmail.com"}]
license = {text = "GPL-3.0-or-later"}

